version: '3.8'

services:
    web:
        image: nginx:latest
        container_name: my-laravel-app
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        image: php:8.1.17-fpm
        container_name: php-container
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel-network

    db:
        image: mysql:latest
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: callJournal
            MYSQL_USER: root
            MYSQL_PASSWORD:
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:

volumes:
    mysql-data:
